### PR TITLE
Registration + Add Bus

### PR DESCRIPTION
**Pull request by YatinGupta777**
Registration frontend is designed

### CODE REVIEW

**Comment by kartik1998** [comment]
Tested all the api's?

**Comment by YatinGupta777** [comment]
Need the backend APIS designed to test on the frontend.

**Comment by kartik1998** [comment]
Yes sure adding all the backend API's in 5 minutes. Sorry had hit a bit of a road block.

**Comment by YatinGupta777** [comment]
Yeah no worries. Please first see my PRs and merge

**Comment by kartik1998** [comment]
cool just a sec

**Comment by kartik1998** [comment]
Great! merging. After that adding my backend

**Pull request merged**
